---

- name: Running workload provision tasks
  when: ACTION | default("provision") == "provision"
  block:

    - name: Validate seed data is defined and is a mapping
      ansible.builtin.assert:
        that:
          - ocp4_workload_showroom_user_data_seed is defined
          - ocp4_workload_showroom_user_data_seed is mapping
        quiet: true
        fail_msg: >-
          Expected ocp4_workload_showroom_user_data_seed to be defined as a mapping.

    - name: Seed AgnosticD user_data for Showroom
      agnosticd.core.agnosticd_user_info:
        data: "{{ ocp4_workload_showroom_user_data_seed }}"

- name: Running workload removal tasks
  when: ACTION | default("provision") == "destroy"
  ansible.builtin.debug:
    msg: >-
      ocp4_workload_showroom_user_data_seed destroy is a no-op.
      User data does not require cleanup.
